app/urls.py
from django.urls import path
from app.views import *

app_name = 'app'

urlpatterns = [
    path('', home_page, name='home'),
    path('details/<slug:slug>', job_detail, name='job_details'),
]

job_app/urls.py
from django.contrib import admin
from django.urls import path, include
from app.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('jobs/', include('app.urls')),
    path('email/', include('subscribe.urls')),
]

subscribe/urls.py
from django.urls import path

from subscribe.views import subscribe_page

urlpatterns = [
    path('', subscribe_page, name='email')
]

app/models.py
from email.policy import default
from django.db import models
from django.utils.text import slugify


# Create your models here.

class Location(models.Model):
    street = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    state = models.CharField(max_length=200)
    zip = models.IntegerField()

    def __str__(self) -> str:
        return self.city


class JobPost(models.Model):
    type_choices = [
        ('Full time', 'Full time'),
        ('Part time', 'Part time'),
        ('Internship', 'Internship'),
    ]

    title = models.CharField(max_length=200)
    date = models.DateTimeField(auto_now_add=True)
    description = models.CharField(max_length=500)
    salary = models.IntegerField()
    type = models.CharField(max_length=10, choices=type_choices, default='Full time')
    slug = models.SlugField(max_length=200, unique=True)
    location = models.OneToOneField(Location, on_delete=models.CASCADE, null=True)

    def __str__(self) -> str:
        return self.title

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title)
        return super(JobPost, self).save(*args, **kwargs)

subscribe/models.py
from django.db import models

# Create your models here.
class Subscribe(models.Model):
    SUBSCRIBE_OPTION = [
        ('M', 'Monthly'),
        ('W', 'Weekly'),
    ]

    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200, unique=True)
    option = models.CharField(max_length=2, default='M', choices=SUBSCRIBE_OPTION)

    def __str__(self) -> str:
        return self.email

subscribe/forms.py
from django import forms
from subscribe.models import Subscribe

class SubscribeForm(forms.ModelForm):
    class Meta:
        model = Subscribe
        fields = '__all__'
        labels = {
            'first_name': 'Enter First Name:',
            'last_name': 'Enter Last Name:',
            'email': 'Enter Email:'
        }
        error_messages = {
            'email': {
                'unique': 'Email already exists',
            }
        }          

app/views.py
from django.shortcuts import render
from app.models import JobPost

# Create your views here.
def home_page(request):
    jobs = JobPost.objects.all()
    context = {
        "jobs" : jobs,
    }
    return render(request, "app/home.html", context=context)


def job_detail(request, slug):
    data = JobPost.objects.get(slug=slug)
    context = {
        "data" : data
    }
    return render(request, 'app/details.html', context=context)

    

subscribe/views.py
from re import sub
from xml.dom import ValidationErr
from django.shortcuts import render
from django import forms
from subscribe.forms import SubscribeForm

# Create your views here.
def subscribe_page(request):
    form = SubscribeForm()
    if request.method == 'POST':
        form = SubscribeForm(request.POST)
        if form.is_valid():
            form.save()
            submitted_form = form.instance
            return render(request, 'subscribe/email.html', context={'submitted_form': submitted_form})
    context = {
        'form': form,
    }
    return render(request, 'subscribe/email.html', context=context)    

app/templates/app/details.html
{% extends 'base.html' %}

{% block title %}
    Job Detail
{% endblock title %}

{% block body %}
<section>
    <div class="container">
      <div class="view-post">
        <h1 class="jobtitle">
          {{ data.title }}
        </h1>
        <p class="location it">Location: <span>{{ data.location }}</span></p>
        <p class="status it">Type: <span>{{ data.type }}</span></p>
        <p class="budget it">Salary: <span>{{ data.salary }}$</span></p>
        <div class="desc">
          <p class="details">
            {{ data.description }}
          </p>
        </div>
      </div>
    </div>
  </section>
{% endblock body %}

app/templates/app/home.html
{% extends 'base.html' %}

{% block title %}
    Job listing
{% endblock title %}

{% block body %}
<section>
    <div class="container">
        {% for job in jobs %}
            <!-- job post -->
            <div class="post">
                <!-- title and des -->
                <div class="job-info">
                <h1 class="job-title">{{ job.title }}</h1>
                <div class="job-des">
                    <div class="location item">
                    <span class="material-icons"> place </span>
                    <p>{{ job.location }}</p>
                    </div>
                    <div class="budget item">
                    <span class="material-icons"> attach_money </span>
                    <p>{{ job.salary }}/Pm</p>
                    </div>
                    <div class="time item">
                    <span class="material-icons"> schedule </span>
                    <p>{{ job.type }}</p>
                    </div>
                </div>
                </div>
                <a href="{% url 'app:job_details' job.slug %}">
                    <div class="buttons">    
                        <button class="apply">
                            View job
                        </button>
                    </div>
                </a>
            </div>
            <!-- job post end-->
        {% endfor %}
    </div>
  </section>
{% endblock body %}

subscribe/templates/subscribe/email.html
{% extends 'base.html' %}

{% block title %}
    Email
{% endblock title %}

{% block body %}
<section>
    <div class="container">
        {% if submitted_form %}
            <center>
                <br>
                <h2>Email Submitted Successfully</h2>
                <br>
                <p>{{ submitted_form.email }}</p>
            </center>
        {% else %}
            <form class='email-form' method='post'>
                {% csrf_token %}
                {{ form }}
                <button class="email-submit">Submit</button>
            </form>
        {% endif %}

    </div>
</section>
{% endblock body %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <link
      href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp"
      rel="stylesheet"
    />
    <title>
        {% block title %}
        
        {% endblock title %}
    </title>
  </head>
  <body>
    <header>
      <nav>
        <div class="container">
          <div class="logo">
            <img src="{% static 'images/logo.svg' %}" alt="" />
          </div>
          <div class="links">
            <a href="{% url 'app:home' %}" onclick="menu()">Home</a>
          </div>
          <span class="material-icons menu" onclick="menu()"> menu </span>
        </div>
      </nav>
    </header>

    {% block body %}

    {% endblock body  %}


    <script src="{% static 'app.js' %}"></script>
  </body>
</html>